env:
  global:
    # COVERALLS_REPO_TOKEN
    - secure: "qNr/n1M4XTvv8P+ae6Xb+obtN+aLmCUecD6HBbpr2bb59WfVUWxUFZqzVqASn2xU8MDGTnvjX8OQQdHJz7PwY/cM446Y3WlusVgWIQFYBzp0Tz9/jVpuHXkClUIixGBAUGM3/Ebs1C/whVcLmDita3kpuxa+MqnyEnug4qngidc="

    # CODECLIMATE_REPO_TOKEN
    - secure: "S+vePO7gncl7oONm7dY6DXUrB7T14J/xJXTBAcMKS4MBUENpRYixCMI5EwY2D+tybaSTLpwA2RfOUXeAvhf33PJeA04n5qdGxiB6RXak15QYkZztwDuJrXQ4yUeSnl3Ij9n2uixUhIvG4g3Xgjq1gVrw32ieadKJbmt+AYGEBPg="

language: node_js

node_js:
  - iojs
  - 0.1

install:
  - npm install

script:
  - make test.coverage.coveralls